import {useEffect,useState} from 'react'
import {api} from '../lib/api'
import {ServiceForm,ErrorState,LoadingState,EmptyState} from '../components/ServiceStates'
import {Conversation,SpecificationCard,type ServiceData} from './OrderCenter'
interface Staff {id:string;name:string;role:string;active:number;revision:number}
interface Material {id:string;name:string;unit:string;stock:number;reserved:number;available:number}
interface Task {id:string;order_id:string;day:string;minutes:number;title:string;assignee:string|null;status:string;revision:number}
interface Operations {role:string;materials:Material[];days:{day:string;capacity:number;used:number}[];tasks:Task[];taskCount:number;staff:Staff[];reservations:{order_id:string;material_id:string;quantity:number;state:string}[];jobs?:{id:string;kind:string;status:string;attempts:number;available:number;last_error:string|null}[];history?:{id:number;created_at:string;actor_id:string;action:string;entity_id:string}[];media?:{backend:string;bytes:number;pending:number}}
type Send=(path:string,body:unknown)=>Promise<unknown>
type Order={id:string;customer:{name:string};stage:string}
export function AdminService({csrf,orders}:{csrf:string;orders:Order[]}){
 const [data,setData]=useState<Operations|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[section,setSection]=useState('center'),[orderId,setOrderId]=useState(''),[from,setFrom]=useState(new Date().toISOString().slice(0,10)),[to,setTo]=useState(new Date(Date.now()+30*86400000).toISOString().slice(0,10))
 async function load(){setLoading(true);setError('');try{setData(await api<Operations>('/api/v1/admin/service?from='+from+'&to='+to))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[from,to])
 const send:Send=async(path,body)=>{const result=await api('/api/v1/admin/service'+path,{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify(body)});await load();return result}
 if(!data)return error?<ErrorState error={error} retry={()=>void load()}/>:<LoadingState/>
 const production=['owner','production'].includes(data.role),commercial=['owner','support'].includes(data.role)
 return <div className="operations-panel">{error&&<ErrorState error={error} retry={()=>void load()}/>} {loading&&<LoadingState>Odświeżamy dane pracowni…</LoadingState>}<nav className="service-tabs" aria-label="Narzędzia pracowni">{[['center','Obsługa zamówienia'],...(production?[['calendar','Plan produkcji'],['inventory','Materiały']]:[]),...(data.role==='owner'?[['team','Zespół'],['jobs','Kolejka i historia']]:[])].map(([v,l])=><button key={v} aria-pressed={section===v} onClick={()=>setSection(v)}>{l}</button>)}</nav>
 {section==='center'&&<><label className="field">Wybierz zamówienie<select value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Wybierz…</option>{orders.map(o=><option key={o.id} value={o.id}>{o.customer.name} · {o.id.slice(0,8)}</option>)}</select></label>{orderId?<AdminOrderCenter key={orderId} id={orderId} send={send} commercial={commercial} production={production} operations={data}/>:<EmptyState title="Wszystkie ustalenia przy zamówieniu">Wybierz zamówienie, aby przygotować wycenę, odpisać klientowi, zarezerwować materiał lub nadać przesyłkę.</EmptyState>}</>}
 {section==='calendar'&&<><h3>Plan produkcji</h3><div className="measure-grid"><label className="field">Od<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Do<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><ServiceForm submit="Ustaw dostępny czas" onSend={f=>send('/capacity',{day:f.get('day'),capacity:Number(f.get('capacity'))})}><div className="measure-grid"><label className="field">Dzień<input type="date" name="day" required/></label><label className="field">Dostępne minuty pracy<input type="number" name="capacity" min="0" max="14400" required/></label></div></ServiceForm><div className="production-calendar">{data.days.length?data.days.map(d=>{const used=d.used;return <article className="day-card" key={d.day}><strong>{d.day}</strong><p>{used} / {d.capacity} min</p><meter value={used} min={0} max={Math.max(1,d.capacity)} aria-label={'Obciążenie '+d.day}/><p>Wolne: {d.capacity-used} min</p></article>}):<EmptyState title="Ustal pierwszy dzień pracy">Wprowadź dostępną liczbę minut, a potem zaplanuj zadania.</EmptyState>}</div><h3>Nowe zadanie</h3><TaskForm send={send} orders={orders} staff={data.staff}/><h3>Zaplanowane zadania</h3>{data.taskCount>500&&<p role="status">Pokazujemy pierwsze 500 z {data.taskCount} zadań. Zawęź zakres dat. Obciążenie dni obejmuje wszystkie zadania.</p>}{data.tasks.map(t=><details className="admin-card" key={t.id+':'+t.revision}><summary>{t.day} · {t.title} · {t.minutes} min · {t.status}</summary><TaskForm task={t} send={send} orders={orders} staff={data.staff}/></details>)}</>}
 {section==='inventory'&&<><h3>Materiały i dodatki</h3><p>Tkaniny zapisujemy w centymetrach (100 cm = 1 m), dodatki w sztukach. Dostępne = stan magazynu minus rezerwacje.</p><div className="table-scroll"><table><thead><tr><th>Materiał</th><th>Stan</th><th>Rezerwacje</th><th>Dostępne</th></tr></thead><tbody>{data.materials.map(m=><tr key={m.id}><th>{m.name}</th><td>{m.stock} {m.unit==='cm'?'cm':'szt.'}</td><td>{m.reserved}</td><td>{m.available}</td></tr>)}</tbody></table></div><StockForm materials={data.materials} send={send}/></>}
 {section==='team'&&<><h3>Uprawnienia zespołu</h3><p>Produkcja zarządza planem, materiałami i etapami. Obsługa prowadzi wyceny, rozmowy i przesyłki. Właściciel ma pełny dostęp. Zmiana roli lub wyłączenie konta kończy jego sesje.</p><p>Nowe konta i reset hasła konfiguruje administrator serwera przez <code>npm run staff:setup</code>. Każdy pracownik ma własne hasło i TOTP.</p>{!data.staff.length&&<EmptyState title="Pracujesz samodzielnie">Główne konto właściciela pozostaje aktywne. Tutaj pojawią się dodane konta pracowników.</EmptyState>}{data.staff.map(s=><article className="admin-card" key={s.id+':'+s.revision}><h3>{s.name}</h3><ServiceForm onSend={f=>send('/staff',{id:s.id,revision:s.revision,role:f.get('role'),active:f.get('active')==='on'})}><label className="field">Rola<select name="role" defaultValue={s.role}><option value="production">Produkcja</option><option value="support">Obsługa klienta</option><option value="owner">Właściciel</option></select></label><label className="check"><input type="checkbox" name="active" defaultChecked={!!s.active}/>Konto aktywne</label></ServiceForm></article>)}</>}
 {section==='jobs'&&<><h3>Kolejka trwałych zadań</h3><p>Media: {data.media?.backend}. Zapisano {((data.media?.bytes||0)/1048576).toFixed(1)} MB; oczekuje na przeniesienie: {data.media?.pending}.</p>{!data.jobs?.length&&<EmptyState title="Brak zadań">Zadania pojawią się po uruchomieniu procesu roboczego lub dodaniu zdjęć i przesyłek.</EmptyState>}{data.jobs?.map(j=><article className="admin-card" key={j.id}><strong>{j.kind} · {j.status}</strong><p>Próby: {j.attempts}. {j.last_error&&'Kod problemu: '+j.last_error}</p>{j.status==='failed'&&(j.kind==='shipment_create'?<p>Sprawdź przesyłkę w panelu InPost, a następnie przypisz jej identyfikator w obsłudze zamówienia. Nie twórz drugiej etykiety.</p>:<ServiceForm submit="Ponów zadanie" onSend={()=>send('/jobs/retry',{id:j.id})}><p>Ponowienie zachowa dane zadania.</p></ServiceForm>)}</article>)}<h3>Historia działań</h3><div className="table-scroll"><table><thead><tr><th>Czas</th><th>Osoba</th><th>Operacja</th><th>Rekord</th></tr></thead><tbody>{data.history?.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString('pl-PL')}</td><td>{data.staff.find(s=>s.id===h.actor_id)?.name||({owner:'Właściciel',customer:'Klient',operator:'Administrator serwera'}[h.actor_id]||h.actor_id)}</td><td>{h.action}</td><td>{h.entity_id}</td></tr>)}</tbody></table></div></>}
 </div>
}
function StockForm({materials,send}:{materials:Material[];send:Send}){
 const [key,setKey]=useState(()=>crypto.randomUUID())
 return <ServiceForm submit="Zapisz ruch magazynowy" onSend={async f=>{await send('/stock',{id:f.get('id')||undefined,name:f.get('name'),unit:f.get('unit'),delta:Number(f.get('delta')),note:f.get('note'),requestKey:key});setKey(crypto.randomUUID())}}><label className="field">Materiał<select name="id" onChange={()=>setKey(crypto.randomUUID())}><option value="">Nowy materiał</option>{materials.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="measure-grid"><label className="field">Nazwa nowego materiału<input name="name" minLength={2} maxLength={120}/></label><label className="field">Jednostka nowego materiału<select name="unit"><option value="cm">Centymetry</option><option value="piece">Sztuki</option></select></label><label className="field">Zmiana stanu (+ dostawa / − korekta)<input type="number" name="delta" required min="-10000000" max="10000000" onChange={()=>setKey(crypto.randomUUID())}/></label></div><label className="field">Powód<input name="note" required minLength={3} maxLength={300}/></label></ServiceForm>
}
function TaskForm({task,orders,staff,send}:{task?:Task;orders:Order[];staff:Staff[];send:Send}){const [newId,setNewId]=useState(()=>crypto.randomUUID());return <ServiceForm resetOnSuccess={!task} onSaved={()=>setNewId(crypto.randomUUID())} submit={task?'Zapisz zadanie':'Zaplanuj zadanie'} onSend={f=>send('/tasks',{id:task?.id||newId,revision:task?.revision||0,orderId:f.get('orderId'),day:f.get('day'),minutes:Number(f.get('minutes')),title:f.get('title'),assignee:f.get('assignee')||null,status:f.get('status')})}><div className="measure-grid"><label className="field">Zamówienie<select name="orderId" required defaultValue={task?.order_id||''}><option value="">Wybierz…</option>{orders.map(o=><option value={o.id} key={o.id}>{o.id.slice(0,8)} · {o.customer.name}</option>)}</select></label><label className="field">Dzień<input name="day" type="date" required defaultValue={task?.day}/></label><label className="field">Czas w minutach<input name="minutes" type="number" required min="1" max="14400" defaultValue={task?.minutes}/></label></div><label className="field">Czynność<input name="title" required minLength={2} maxLength={200} defaultValue={task?.title}/></label><div className="measure-grid"><label className="field">Osoba<select name="assignee" defaultValue={task?.assignee||''}><option value="">Nieprzypisane / właściciel</option>{staff.filter(s=>s.active&&s.role!=='support').map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Stan<select name="status" defaultValue={task?.status||'planned'}><option value="planned">Zaplanowane</option><option value="done">Wykonane</option><option value="cancelled">Anulowane</option></select></label></div></ServiceForm>}
function AdminOrderCenter({id,send,commercial,production,operations}:{id:string;send:Send;commercial:boolean;production:boolean;operations:Operations}){
 const [data,setData]=useState<ServiceData|null>(null),[error,setError]=useState('')
 async function load(){try{setData(await api<ServiceData>('/api/v1/admin/service/orders/'+id));setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[id])
 const submit:Send=async(path,body)=>{const result=await send(path,body);await load();return result}
 if(!data)return error?<ErrorState error={error} retry={()=>void load()}/>:<LoadingState/>
 return <>{error&&<ErrorState error={error} retry={()=>void load()}/>}<h3>Zamówienie {id.slice(0,8)}</h3><button type="button" onClick={()=>void load()}>Odśwież rozmowę i ustalenia</button><details className="admin-card" open><summary>Specyfikacja i wyceny</summary>{data.specifications.map(s=><SpecificationCard key={s.id} spec={s}/>)}{commercial&&<ServiceForm submit="Wyślij nową wersję do akceptacji" onSend={f=>submit('/orders/'+id+'/specifications',{previousVersion:data.specifications[0]?.version||0,amount:Math.round(Number(f.get('amount'))*100),estimatedDate:f.get('date'),validDays:Number(f.get('days')),description:f.get('description'),measurements:f.get('measurements'),material:f.get('material'),delivery:f.get('delivery')})}><label className="field">Opis wykonania<textarea name="description" required minLength={5} maxLength={4000}/></label><label className="field">Pomiary i sposób mierzenia<textarea name="measurements" maxLength={1000}/></label><label className="field">Materiał<input name="material" required minLength={2} maxLength={300}/></label><label className="field">Uzgodniona dostawa<input name="delivery" required minLength={2} maxLength={500}/></label><div className="measure-grid"><label className="field">Łączna cena z dostawą (PLN)<input type="number" name="amount" step="0.01" min="0.01" max="100000" required/></label><label className="field">Przewidywany termin<input type="date" name="date" required/></label><label className="field">Ważność oferty (dni)<input type="number" name="days" min="1" max="30" defaultValue="7" required/></label></div><p>Nowa wersja zastąpi poprzednią oczekującą ofertę. Zaakceptowane wersje pozostaną w historii.</p></ServiceForm>}</details><details className="admin-card"><summary>Wiadomości</summary><Conversation orderId={'admin-'+id} messages={data.messages} readOnly={!commercial} send={body=>submit('/orders/'+id+'/messages',body)}/></details>
 {production&&<details className="admin-card"><summary>Materiały do tego zamówienia</summary><ServiceForm submit="Zapisz komplet rezerwacji" onSend={f=>submit('/orders/'+id+'/reservations',{items:operations.materials.map(m=>({materialId:m.id,quantity:Number(f.get(m.id))})).filter(m=>m.quantity>0)})}>{operations.materials.map(m=><label className="field" key={m.id}>{m.name} ({m.unit}) — wolne: {m.available}<input name={m.id} type="number" min="0" max="10000000" defaultValue={data.reservations?.find(r=>r.order_id===id&&r.material_id===m.id&&r.state==='reserved')?.quantity||0}/></label>)}<p>Zapis zastępuje cały zestaw rezerwacji. Wpisz 0, aby zwolnić dany materiał.</p></ServiceForm><ServiceForm submit="Rozlicz materiały" onSend={f=>submit('/orders/'+id+'/materials',{action:f.get('action')})}><label className="field">Operacja<select name="action"><option value="consume">Materiały zużyto — odejmij ze stanu</option><option value="release">Zwolnij rezerwacje bez zużycia</option></select></label><label className="check"><input type="checkbox" required/>Potwierdzam operację magazynową.</label></ServiceForm></details>}
 {commercial&&<details className="admin-card"><summary>Przesyłka i etykieta</summary>{data.shipment?<><p>InPost · {data.shipment.environment} · {data.shipment.status}</p><p>Numer: {data.shipment.tracking_number||'Oczekuje'}</p><ServiceForm submit="Pobierz aktualny status do kolejki" onSend={()=>submit('/shipments/'+data.shipment!.id+'/refresh',{})}><p>Odśwież widok po wykonaniu zadania.</p></ServiceForm>{data.shipment.provider_id?<a className="btn" href={'/api/v1/admin/service/shipments/'+data.shipment.id+'/label'}>Pobierz etykietę PDF</a>:<ServiceForm submit="Przypisz istniejącą przesyłkę" onSend={f=>submit('/shipments/'+data.shipment!.id+'/reconcile',{providerId:f.get('providerId')})}><p>Jeśli zadanie nie powiodło się, znajdź przesyłkę w InPost po numerze zamówienia. Podaj ID ShipX, nie numer śledzenia.</p><label className="field">ID ShipX<input name="providerId" inputMode="numeric" pattern="[0-9]+" required/></label></ServiceForm>}</>:<ShipmentForm id={id} send={submit}/>}</details>}</>
}
function ShipmentForm({id,send}:{id:string;send:Send}){return <ServiceForm submit="Zleć przygotowanie przesyłki" onSend={f=>send('/orders/'+id+'/shipment',Object.fromEntries([...f.entries()].map(([k,v])=>[k,['length','width','height','weightGrams'].includes(k)?Number(v):k==='confirmCost'?v==='on':v])))}><p>Kurier InPost w Polsce. Zamówienie musi być oznaczone jako gotowe. Dane nadawcy pobierane są z konta organizacji InPost.</p><div className="admin-grid">{[['firstName','Imię odbiorcy'],['lastName','Nazwisko odbiorcy'],['phone','Telefon'],['street','Ulica'],['buildingNumber','Numer budynku / lokalu'],['city','Miasto'],['postalCode','Kod pocztowy']].map(([n,l])=><label className="field" key={n}>{l}<input name={n} required maxLength={100}/></label>)}</div><div className="measure-grid">{[['length','Długość (mm)',1500],['width','Szerokość (mm)',1500],['height','Wysokość (mm)',1500],['weightGrams','Masa (g)',25000]].map(([n,l,max])=><label className="field" key={n}>{l}<input name={String(n)} type="number" min="1" max={max} required/></label>)}</div><label className="check"><input type="checkbox" name="confirmCost" required/>Sprawdziłem dane. W środowisku produkcyjnym etykieta może obciążyć konto pracowni zgodnie z umową InPost. Nie pobieramy płatności od klienta na stronie.</label></ServiceForm>}
