import {useEffect,useRef,useState,type ChangeEvent} from 'react'
import {api} from '../lib/api'
import {useEditorial,type EditorialDocument,type EditorialSection} from '../state/editorial'
import {useProducts} from '../state/store'
import {EditorialHero,EditorialSections} from './Editorial'
interface Row {id:string;kind:'drop'|'page';draft:EditorialDocument;live:EditorialDocument|null;pending:EditorialDocument|null;pending_at:string|null;revision:number;deleted:number;interested:number}
interface Snapshot {id:number;document_id:string;revision:number;actor:string;action:string;created_at:string}
interface Asset {id:string;src:string;mime:string}
interface Dashboard {documents:Row[];history:Snapshot[];media:Asset[]}
const newDrop=():EditorialDocument=>({kind:'drop',slug:'nowy-drop',title:'Nowy drop',description:'',eyebrow:'MARIANO / NOWA KOLEKCJA',image:'',mobileImage:'',video:'',alt:'',theme:'dark',layout:'grid',height:'large',align:'left',overlay:35,focalX:50,focalY:50,position:0,ctaLabel:'Odkryj kolekcję',ctaHref:'/shop',enabled:true,showHome:true,showProducts:true,showDate:true,showCountdown:true,showWaitlist:false,showArchive:true,productSlugs:[],sections:[]})
function localDate(value?:string|null){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function utcDate(value:string){return value?new Date(value).toISOString():''}
export function AdminEditorial({csrf,upload}:{csrf:string;upload:(file:File)=>Promise<{id:string;src:string;mime:string}>}){
 const {refresh}=useEditorial(),products=useProducts()
 const [data,setData]=useState<Dashboard|null>(null),[row,setRow]=useState<Row|null>(null),[draft,setDraft]=useState<EditorialDocument|null>(null),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[publishAt,setPublishAt]=useState(''),[preview,setPreview]=useState(false),[phone,setPhone]=useState(false),[confirm,setConfirm]=useState('')
 const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{void load()},[])
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty])
 useEffect(()=>{if(preview)dialog.current?.showModal();else dialog.current?.close()},[preview])
 async function load(selectId?:string){try{const next=await api<Dashboard>('/api/admin/editorial');setData(next);if(selectId){const selected=next.documents.find(r=>r.id===selectId)!;setRow(selected);setDraft(selected.draft);setPublishAt(localDate(selected.pending_at));setDirty(false)}}catch(e){setError((e as Error).message)}}
 function choose(value:Row|null){if(dirty&&!window.confirm('Porzucić niezapisane zmiany?'))return;setRow(value);setDraft(value?structuredClone(value.draft):newDrop());setPublishAt(localDate(value?.pending_at));setDirty(false);setError('');setNotice('');setConfirm('')}
 function patch(value:Partial<EditorialDocument>){setDraft(d=>({...d!,...value}));setDirty(true)}
 async function execute(action:string,historyId?:number){if(!draft||busy)return;setBusy(true);setError('');setNotice('');try{const result=await api<{id:string}>('/api/admin/editorial'+(row?'/'+row.id:''),{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({action,revision:row?.revision,document:draft,publishAt:publishAt?utcDate(publishAt):'',historyId})});await load(result.id);refresh();setConfirm('');setNotice(({save:'Wersja robocza zapisana.',publish:'Opublikowano.',schedule:'Publikacja zaplanowana.',delete:'Drop przeniesiony do kosza.',restore:'Wersja przywrócona do edycji. Opublikuj ją, gdy będzie gotowa.',cancel:'Harmonogram anulowany.',unpublish:'Wycofano ze strony.'} as Record<string,string>)[action])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function sectionPatch(index:number,value:Partial<EditorialSection>){patch({sections:draft!.sections.map((s,i)=>i===index?{...s,...value}:s)})}
 function move(index:number,offset:number){const sections=[...draft!.sections];[sections[index],sections[index+offset]]=[sections[index+offset],sections[index]];patch({sections})}
 async function file(event:ChangeEvent<HTMLInputElement>,field:'image'|'mobileImage'|'video',section?:number){const selected=event.target.files?.[0];event.target.value='';if(!selected)return;setBusy(true);setError('');try{const asset=await upload(selected);if(field==='video'&&asset.mime!=='video/mp4'||field!=='video'&&asset.mime==='video/mp4')throw Error('Wybierz właściwy typ pliku.');if(section===undefined)patch({[field]:asset.src});else sectionPatch(section,{[field]:asset.src});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const mediaField=(field:'image'|'mobileImage'|'video',label:string,index?:number)=>{const value=index===undefined?draft?.[field]:(field==='video'?undefined:draft?.sections[index]?.[field]);return <div className="cms-media-field"><label className="field">{label}<input value={String(value||'')} placeholder="/media/…" maxLength={250} onChange={e=>index===undefined?patch({[field]:e.target.value}):sectionPatch(index,{[field]:e.target.value})}/></label><label className="field">Prześlij plik<input type="file" accept={field==='video'?'video/mp4':'image/jpeg,image/png,image/webp'} onChange={e=>void file(e,field,index)}/></label><label className="field">Lub wybierz z biblioteki<select value="" onChange={e=>index===undefined?patch({[field]:e.target.value}):sectionPatch(index,{[field]:e.target.value})}><option value="">Wybierz plik</option>{data?.media.filter(a=>field==='video'?a.mime==='video/mp4':a.mime!=='video/mp4').map(a=><option key={a.id} value={a.src}>{a.id.slice(0,8)} · {a.mime}</option>)}</select></label></div>}
 const selectProducts=(values:string[],change:(values:string[])=>void)=><div className="cms-products">{products.map(p=><label className="check" key={p.slug}><input type="checkbox" checked={values.includes(p.slug)} onChange={e=>change(e.target.checked?[...values,p.slug]:values.filter(v=>v!==p.slug))}/>{p.name}</label>)}<p className="small">Kolejność zaznaczania ustala kolejność produktów.</p></div>
 return <div className="cms"><div className="cms-heading"><div><h2>Studio publikacji</h2><p>Dropy, kampanie i strony. Najpierw projekt, potem publikacja.</p></div><button className="btn" disabled={busy} onClick={()=>choose(null)}>Nowy drop</button></div>{error&&<div role="alert" className="error">{error}<button onClick={()=>void load()}>Odśwież listę</button></div>}<p role="status">{notice}</p><div className="cms-workspace"><aside className="cms-sidebar">{!data?<p>Wczytujemy dokumenty…</p>:data.documents.map(r=><button key={r.id} disabled={busy} aria-pressed={row?.id===r.id} onClick={()=>choose(r)}><strong>{r.draft.title}</strong><span>{r.kind==='page'?'Strona':'Drop'} · {r.deleted?'Kosz':r.pending?'Zaplanowano':r.live?'Publiczny':'Roboczy'}</span></button>)}</aside>{draft?<div className="cms-editor"><div className="cms-toolbar"><span>{dirty?'Niezapisane zmiany':row?'Wersja '+row.revision:'Nowy projekt'}</span><button disabled={busy} onClick={()=>setPreview(true)}>Podgląd</button><button disabled={busy} onClick={()=>{setDraft({...structuredClone(draft),kind:'drop',slug:draft.slug+'-kopia',title:draft.title+' — kopia'});setRow(null);setDirty(true)}}>Duplikuj jako drop</button></div><fieldset disabled={busy}><details open><summary>Treść i adres</summary><div className="admin-grid">{(['title','slug','eyebrow','description','badge','ctaLabel','ctaHref','seoTitle','seoDescription'] as const).map((key,i)=><label className="field" key={key}>{['Tytuł (do 100 znaków)','Adres (slug)','Nadtytuł','Krótki opis','Etykieta dropu','Tekst przycisku','Link przycisku','Tytuł dla wyszukiwarki','Opis dla wyszukiwarki'][i]}<textarea value={draft[key]||''} disabled={key==='slug'&&row?.kind==='page'} maxLength={key==='description'?400:key==='seoDescription'?200:key==='ctaLabel'||key==='badge'?40:key==='slug'||key==='eyebrow'?80:100} onChange={e=>patch({[key]:e.target.value})}/></label>)}</div></details>
 <details open><summary>Zdjęcia i film</summary>{mediaField('image','Główne zdjęcie')}{mediaField('mobileImage','Osobny kadr na telefon')}{mediaField('video','Film MP4 (opcjonalny)')}<label className="field">Opis zdjęcia<input value={draft.alt||''} maxLength={300} onChange={e=>patch({alt:e.target.value})}/></label><p className="small">Materiały mają pochodzić z Twojej kolekcji. Ilustracje AI nie są dokumentacją produktu. Limit przesyłania: 12 MB. Dla filmu z mową przygotuj napisy w samym materiale.</p></details>
 <details><summary>Wygląd sekcji</summary><div className="admin-grid">{([{key:'theme',label:'Kolor',values:[['dark','Ciemny'],['light','Jasny']]},{key:'layout',label:'Układ produktów',values:[['grid','Siatka'],['split','Dwie kolumny'],['wide','Duże kadry']]},{key:'height',label:'Wysokość okładki',values:[['full','Pełny ekran'],['large','Duża'],['compact','Kompaktowa']]},{key:'align',label:'Wyrównanie tekstu',values:[['left','Do lewej'],['center','Centralnie'],['right','Do prawej']]}] as const).map(f=><label className="field" key={f.key}>{f.label}<select value={draft[f.key]||f.values[0][0]} onChange={e=>patch({[f.key]:e.target.value})}>{f.values.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}{(['overlay','focalX','focalY'] as const).map((key,i)=><label className="field" key={key}>{['Przyciemnienie zdjęcia','Kadr w poziomie','Kadr w pionie'][i]}: {draft[key]??(key==='overlay'?35:50)}%<input type="range" min="0" max={key==='overlay'?80:100} value={draft[key]??(key==='overlay'?35:50)} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}<label className="field">Pozycja na liście<input type="number" min="0" max="999" value={draft.position||0} onChange={e=>patch({position:Number(e.target.value)})}/></label></div></details>
 <details open><summary>Premiera i widoczność</summary><div className="admin-grid">{(['launchAt','endsAt'] as const).map((key,i)=><label className="field" key={key}>{['Premiera kolekcji','Koniec dropu / przejście do archiwum'][i]}<input type="datetime-local" value={localDate(draft[key])} onChange={e=>patch({[key]:utcDate(e.target.value)})}/></label>)}</div><p className="small">Daty wpisujesz w strefie swojego urządzenia ({Intl.DateTimeFormat().resolvedOptions().timeZone}). Klienci widzą czas polski. Premiera nie zmienia dostępności produktu — ustaw ją w zakładce Produkty.</p>{(['enabled','showHome','showDate','showCountdown','showProducts','showWaitlist','showArchive'] as const).map((key,i)=><label className="check" key={key}><input type="checkbox" checked={draft[key]!==false&&(key!=='showWaitlist'||draft[key]===true)} onChange={e=>patch({[key]:e.target.checked})}/>{['Sekcja aktywna','Pokaż drop na głównej','Pokaż datę premiery','Odliczanie do premiery','Pokaż produkty na stronie dropu','Zapisy zainteresowanych (potwierdzenie e-mail)','Zachowaj zakończony drop w archiwum'][i]}</label>)}{row&&<p>Potwierdzeni zainteresowani: {row.interested}. Kampanię do tej grupy przygotujesz po uruchomieniu poczty; publikacja sama nie wysyła newslettera.</p>}</details>
 <details><summary>Produkty kolekcji</summary>{selectProducts(draft.productSlugs||[],productSlugs=>patch({productSlugs}))}</details>
 <details open><summary>Sekcje strony ({draft.sections.length}/24)</summary>{draft.sections.map((s,i)=><div className="cms-section-editor" key={s.id}><div className="cms-toolbar"><strong>{i+1}. {s.title||'Sekcja'}</strong><button disabled={!i} onClick={()=>move(i,-1)} aria-label="Przesuń sekcję w górę">↑</button><button disabled={i===draft.sections.length-1} onClick={()=>move(i,1)} aria-label="Przesuń sekcję w dół">↓</button><button onClick={()=>patch({sections:draft.sections.filter((_,n)=>n!==i)})}>Usuń sekcję</button></div><label className="check"><input type="checkbox" checked={s.enabled} onChange={e=>sectionPatch(i,{enabled:e.target.checked})}/>Widoczna</label><div className="admin-grid"><label className="field">Typ<select value={s.type} onChange={e=>sectionPatch(i,{type:e.target.value as EditorialSection['type']})}>{[['text','Tekst'],['image','Zdjęcie i tekst'],['products','Produkty'],['drops','Dropy na głównej'],['cloth','Studium tkaniny 3D']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field">Tło<select value={s.theme||'light'} onChange={e=>sectionPatch(i,{theme:e.target.value as 'light'|'dark'})}><option value="light">Jasne</option><option value="dark">Ciemne</option></select></label><label className="field">Tytuł<input value={s.title} maxLength={100} onChange={e=>sectionPatch(i,{title:e.target.value})}/></label><label className="field">Tekst<textarea value={s.text||''} maxLength={800} onChange={e=>sectionPatch(i,{text:e.target.value})}/></label><label className="field">Przycisk<input value={s.ctaLabel||''} maxLength={40} onChange={e=>sectionPatch(i,{ctaLabel:e.target.value})}/></label><label className="field">Link<input value={s.ctaHref||''} onChange={e=>sectionPatch(i,{ctaHref:e.target.value})}/></label></div>{s.type==='image'&&<>{mediaField('image','Zdjęcie',i)}{mediaField('mobileImage','Kadr mobilny',i)}<label className="field">Opis zdjęcia<input value={s.alt||''} maxLength={300} onChange={e=>sectionPatch(i,{alt:e.target.value})}/></label></>}{s.type==='products'&&selectProducts(s.productSlugs||[],productSlugs=>sectionPatch(i,{productSlugs}))}{s.type==='drops'&&<label className="field">Liczba dropów<input type="number" min="1" max="12" value={s.limit||4} onChange={e=>sectionPatch(i,{limit:Number(e.target.value)})}/></label>}</div>)}<button disabled={draft.sections.length>=24} onClick={()=>patch({sections:[...draft.sections,{id:crypto.randomUUID(),type:'text',title:'Nowa sekcja',text:'',enabled:true,theme:'light'}]})}>Dodaj sekcję</button></details>
 <div className="cms-publish"><button className="btn" onClick={()=>void execute('save')}>{busy?'Zapisujemy…':'Zapisz roboczą'}</button>{row&&<><button onClick={()=>void execute('publish')}>Opublikuj teraz</button><label className="field">Publikacja wersji roboczej<input type="datetime-local" value={publishAt} onChange={e=>setPublishAt(e.target.value)}/></label><button disabled={!publishAt} onClick={()=>void execute('schedule')}>Zaplanuj publikację</button>{row.pending&&<button onClick={()=>void execute('cancel')}>Anuluj harmonogram</button>}{row.live&&<button onClick={()=>setConfirm('unpublish')}>Wycofaj publikację</button>}{row.kind==='drop'&&!row.deleted&&<button onClick={()=>setConfirm('delete')}>Usuń drop</button>}</>}{confirm&&<div role="alert"><p>{confirm==='delete'?'Usunąć drop ze strony i przenieść do kosza? Historia pozostanie dostępna.':'Wycofać dokument z publicznej strony?'}</p><button onClick={()=>void execute(confirm)}>Potwierdzam</button><button onClick={()=>setConfirm('')}>Anuluj</button></div>}</div>
 <details><summary>Historia i przywracanie</summary>{data?.history.filter(h=>h.document_id===row?.id).map(h=><div className="cms-history" key={h.id}><span>Wersja {h.revision} · {h.action} · {new Date(h.created_at).toLocaleString('pl-PL')} · {h.actor}</span><button onClick={()=>{if(window.confirm('Zastąpić wersję roboczą tą wersją? Publiczna strona się nie zmieni.'))void execute('restore',h.id)}}>Przywróć do edycji</button></div>)}{!row&&<p>Historia pojawi się po pierwszym zapisie.</p>}</details></fieldset></div>:<p className="empty">Wybierz stronę lub utwórz pierwszy drop.</p>}</div>
 <details className="cms-library"><summary>Biblioteka mediów — ostatnie 200 plików</summary><div className="cms-asset-grid">{data?.media.map(a=><div key={a.id}>{a.mime==='video/mp4'?<video controls preload="none" src={a.src}/>:<img src={a.src+'?size=thumb'} alt="Przesłany materiał" loading="lazy"/>}<code>{a.src}</code></div>)}</div></details>
 <dialog ref={dialog} className="cms-preview" onCancel={()=>setPreview(false)}><div className="cms-toolbar"><strong>Podgląd wersji roboczej</strong><button aria-pressed={phone} onClick={()=>setPhone(p=>!p)}>{phone?'Widok szeroki':'Widok 390 px'}</button><button onClick={()=>setPreview(false)}>Zamknij</button></div>{draft&&<div className="cms-preview__canvas" data-phone={phone} onClickCapture={e=>{if((e.target as HTMLElement).closest('a')){e.preventDefault();e.stopPropagation()}}}><EditorialHero document={phone&&draft.mobileImage?{...draft,image:draft.mobileImage}:draft} preview/><EditorialSections sections={draft.sections} preview/>{draft.showProducts&&<p className="shell">Produkty: {(draft.productSlugs||[]).map(slug=>products.find(p=>p.slug===slug)?.name).join(', ')||'Brak wybranych produktów'}</p>}</div>}</dialog>
 </div>
}
