import {useState} from 'react'
import {Link} from 'react-router-dom'
import {PageHeading} from './Pages'
import {useDraft} from '../components/ServiceStates'
const steps=[
 {key:'waist',title:'Obwód pasa',instruction:'Stań swobodnie. Owiń miękką miarkę wokół naturalnego przewężenia talii. Trzymaj ją poziomo, bez ściskania ciała. Oddychaj normalnie.',check:'Nie wciągaj brzucha i nie dodawaj zapasu. Jeśli spodnie mają leżeć niżej, dopisz wysokość pasa w uwagach do personalizacji.'},
 {key:'hips',title:'Obwód bioder',instruction:'Złącz stopy. Poprowadź miarkę wokół najszerszego miejsca bioder i pośladków. Sprawdź w lustrze, czy z tyłu nie biegnie wyżej.',check:'Miarka przylega do lekkiej odzieży lub bielizny, ale nie uciska. Zapisz cały obwód, bez mnożenia przez dwa.'},
 {key:'inseam',title:'Wewnętrzna długość nogawki',instruction:'Połóż dobrze leżące spodnie płasko. Wygładź nogawkę bez rozciągania. Zmierz wzdłuż wewnętrznego szwu, od skrzyżowania szwów w kroku do dolnej krawędzi.',check:'To wymiar spodni. Wybierz parę o oczekiwanej długości; pomiar od pasa po zewnętrznej stronie nie jest tym samym.'}
]
export function MeasurementGuide(){
 const [step,setStep]=useState(0),[done,setDone]=useState(false),draft=useDraft('workshop.measurements'),current=steps[step]
 return <><PageHeading eyebrow="Dopasowanie / krok po kroku" title="Zmierz. Sprawdź. Zapisz." text="Trzy pomiary, które pomagają pracowni dobrać proporcje Twojej pary."/><section className="shell section solid-stage measure-guide"><div className="measure-intro"><h2>Zanim zaczniesz</h2><p>Przygotuj miękką miarkę, lustro i dobrze leżące spodnie. Zmierz każde miejsce dwa razy. Jeżeli wyniki się różnią, powtórz pomiar. Nie dodawaj luzu — uwzględnia go krój i wybrana preferencja dopasowania.</p><p>Wyniki przechowujemy wyłącznie w tej karcie przeglądarki, do 24 godzin. Możesz je usunąć w każdej chwili.</p></div><nav className="measure-steps" aria-label="Etapy mierzenia">{steps.map((s,i)=><button type="button" key={s.key} aria-current={step===i?'step':undefined} onClick={()=>{setStep(i);setDone(false)}}><span>0{i+1}</span>{s.title}</button>)}</nav><div className="measure-card"><p className="eyebrow">Krok {step+1} z 3</p><h2>{current.title}</h2><p>{current.instruction}</p><p className="notice">{current.check}</p><form onSubmit={e=>{e.preventDefault();if(step<2)setStep(step+1);else setDone(true)}}><label className="field" htmlFor="measurement-value">Wynik w centymetrach<input key={current.key} id="measurement-value" type="number" min="20" max="250" step="0.5" required value={draft.value[current.key]||''} onChange={e=>draft.update(current.key,e.target.value)}/></label><button className="btn">{step<2?'Zapisz i przejdź dalej':'Zapisz pomiary'}</button></form></div><div className="measure-summary"><h2>Twoje pomiary</h2><dl>{steps.map(s=><div key={s.key}><dt>{s.title}</dt><dd>{draft.value[s.key]?draft.value[s.key]+' cm':'Jeszcze nie zmierzono'}</dd></div>)}</dl><p role="status">{done?'Pomiary zapisane w tej karcie. Możesz użyć ich w asystencie produktu lub personalizacji.':''}</p><Link className="btn" to="/shop">Przejdź do modeli</Link><button type="button" onClick={()=>{draft.clear();setDone(false)}}>Usuń moje pomiary</button></div><details><summary>Obwody ciała a wymiary gotowych spodni</summary><p>Pas i biodra powyżej to obwody ciała. Tabela konkretnego modelu pokazuje gotowe spodnie, z luzem potrzebnym do poruszania. Mierząc spodnie na płasko, podwój szerokość pasa i bioder; długości nogawki nie podwajaj. Dla elastycznego pasa porównaj także zakres rozciągnięcia podany przez pracownię.</p><p>Jeśli pomiar lub położenie pasa budzi wątpliwości, <Link to="/contact">zapytaj pracownię</Link>. Nie wybieraj rozmiaru na podstawie samej litery na metce.</p></details></section></>
}
