import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {api,post,ApiError,type Quote} from '../lib/api'
import {formatPrice} from '../data/collection'
import {PageHeading} from './Pages'
import {stageNames,ProtectedPhoto} from './Workshop'
import {LoadingState,ErrorState,EmptyState,ServiceForm,useDraft} from '../components/ServiceStates'
export interface Specification {id:string;version:number;content:{description:string;measurements:string;material:string;delivery:string};amount:number;estimated_date:string;expires:number;status:string;created_at:string;decided_at:string|null}
export interface ServiceData {reservations?:{order_id:string;material_id:string;quantity:number;state:string}[];specifications:Specification[];messages:{id:string;author:string;content:string;created_at:string}[];shipment:{id?:string;provider:string;provider_id?:string;tracking_number:string|null;status:string;updated_at:string;environment:string}|null;original:Quote;paymentStatus:string}
interface Center extends ServiceData {id:string;stage:string;estimatedDate:string|null;products:{name:string;size:string;variant:string;quantity:number}[];events:{id:string;created_at:string;stage:string;note:string;photos:string[]}[]}
const statuses:Record<string,string>={offered:'Czeka na decyzję',accepted:'Zaakceptowano',changes_requested:'Poproszono o zmianę',superseded:'Zastąpiono nowszą wersją'}
export function SpecificationCard({spec:s,children}:{spec:Specification;children?:React.ReactNode}){return <article className="spec-card"><div className="tool-heading"><h3>Specyfikacja v{s.version}</h3><span className="status-tag">{s.status==='offered'&&s.expires<Date.now()?'Wygasła':statuses[s.status]}</span></div><p className="spec-amount">{formatPrice(s.amount)} <small>łącznie z ustaloną dostawą</small></p><dl><div><dt>Wykonanie</dt><dd>{s.content.description}</dd></div><div><dt>Materiał</dt><dd>{s.content.material}</dd></div><div><dt>Pomiary</dt><dd>{s.content.measurements||'Zgodnie z wybranym rozmiarem'}</dd></div><div><dt>Dostawa</dt><dd>{s.content.delivery}</dd></div><div><dt>Przewidywany termin</dt><dd>{s.estimated_date}</dd></div></dl><p>Oferta ważna do {new Date(s.expires).toLocaleString('pl-PL')}.{s.decided_at&&' Decyzja: '+new Date(s.decided_at).toLocaleString('pl-PL')}</p>{children}</article>}
export function Conversation({orderId,messages,send,readOnly=false}:{orderId:string;messages:ServiceData['messages'];send:(body:unknown)=>Promise<unknown>;readOnly?:boolean}){
 const draft=useDraft('workshop.message.'+orderId),[requestKey,setRequestKey]=useState(()=>draft.value.requestKey||crypto.randomUUID())
 return <><h3>Rozmowa z pracownią</h3>{messages.length?<ol className="conversation">{messages.map(m=><li key={m.id} data-author={m.author}><strong>{m.author==='customer'?'Klient':'Pracownia'}</strong><time dateTime={m.created_at}>{new Date(m.created_at).toLocaleString('pl-PL')}</time><p>{m.content}</p></li>)}</ol>:<EmptyState title="Tu zaczyna się rozmowa">Zapytaj o szczegóły wykonania lub przekaż uwagi do zamówienia.</EmptyState>}{!readOnly&&<ServiceForm submit="Wyślij wiadomość" onSend={async()=>{await send({content:draft.value.content||'',requestKey});draft.clear();setRequestKey(crypto.randomUUID())}}><label className="field">Twoja wiadomość<textarea required maxLength={3000} value={draft.value.content||''} onChange={e=>{const next=crypto.randomUUID();draft.update('content',e.target.value);draft.update('requestKey',next);setRequestKey(next)}}/></label><p className="small">Szkic pozostaje w tej karcie do 24 godzin. Nie podawaj haseł ani danych płatniczych.</p></ServiceForm>}</>
}
export function OrderCenter(){
 const [key,setKey]=useState<{id:string;token:string}|null>(null),[data,setData]=useState<Center|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[attempt,setAttempt]=useState(0),[tab,setTab]=useState('summary'),[recovered,setRecovered]=useState(''),[initialized,setInitialized]=useState(false)
 useEffect(()=>{try{const fragment=window.location.hash.slice(1),match=fragment.match(/^([a-f0-9-]{36})\.([a-f0-9]{64})$/);if(match){const value={id:match[1],token:match[2]};setKey(value);window.history.replaceState(null,'',window.location.pathname);try{sessionStorage.setItem('workshop.tracking',JSON.stringify(value))}catch{}}else{const value=JSON.parse(sessionStorage.getItem('workshop.tracking')||sessionStorage.getItem('workshop.receipt.v1')||'null');if(value?.id&&value?.token)setKey(value)}}catch{setError('Nie można odczytać zapisanego dostępu. Otwórz link z e-maila.')}finally{setInitialized(true)}},[])
 const refresh=()=>setAttempt(n=>n+1)
 useEffect(()=>{if(!key)return;let active=true;setLoading(true);setError('');api<Center>('/api/v1/service/orders/'+key.id,{headers:{Authorization:'Bearer '+key.token}}).then(r=>{if(active)setData(r)}).catch(e=>{if(active){setError(e.message);if(e instanceof ApiError&&[401,404].includes(e.status))setData(null)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[key,attempt])
 async function send(suffix:string,body:unknown){if(!key)throw Error('Otwórz prywatny link.');const result=await api('/api/v1/service/orders/'+key.id+'/'+suffix,{method:'POST',headers:{Authorization:'Bearer '+key.token},body:JSON.stringify(body)});refresh();return result}
 function forget(){try{sessionStorage.removeItem('workshop.tracking');sessionStorage.removeItem('workshop.receipt.v1');if(key)sessionStorage.removeItem('workshop.message.'+key.id)}catch{}setKey(null);setData(null);setError('')}
 const accepted=data?.specifications.find(s=>s.status==='accepted')
 return <><PageHeading eyebrow="Twoja para / centrum obsługi" title="Wszystkie ustalenia. Jedno miejsce." text="Sprawdź wycenę, porozmawiaj z pracownią i zobacz, jak powstaje Twoje zamówienie."/><section className="shell section solid-stage tracking-page">{error&&<ErrorState error={error} retry={key?refresh:undefined}/>} {loading&&<LoadingState>{data?'Odświeżamy — poniżej ostatnio pobrane dane.':'Otwieramy Twoje zamówienie…'}</LoadingState>}
 {data&&key?<><div className="tracking-summary"><p className="eyebrow">Zamówienie {data.id}</p><h2>{stageNames[data.stage]}</h2><div className="service-metrics"><div><span>Przewidywany termin</span><strong>{data.estimatedDate||'Do uzgodnienia'}</strong></div><div><span>{accepted?'Zaakceptowana wycena':'Wartość zgłoszenia'}</span><strong>{accepted?formatPrice(accepted.amount):data.original.total?formatPrice(data.original.total):'Do wyceny'}</strong></div><div><span>Płatność</span><strong>Nie pobrano</strong></div></div><p>Termin jest szacunkiem pracowni. Płatności na stronie pozostają wyłączone.</p></div><nav className="service-tabs" aria-label="Centrum zamówienia">{[['summary','Podsumowanie'],['specifications','Wyceny i wymiary'],['messages','Wiadomości'],['progress','Realizacja'],['shipment','Przesyłka']].map(([v,l])=><button key={v} aria-pressed={tab===v} onClick={()=>setTab(v)}>{l}</button>)}</nav>
 {tab==='summary'&&<><h3>Twoja para</h3>{data.products.map((p,i)=><article className="service-state" key={i}><strong>{p.name}</strong><p>{p.size} · {p.variant} · {p.quantity} szt.</p></article>)}<p>{accepted?'Ustalenia znajdują się w zaakceptowanej specyfikacji v'+accepted.version+'.':'Pracownia sprawdzi zgłoszenie i potwierdzi możliwości wykonania.'}</p>{data.specifications[0]?.status==='offered'&&<button className="btn" onClick={()=>setTab('specifications')}>Przejrzyj nową wycenę</button>}<Link to="/size-guide">Sprawdź instrukcję mierzenia</Link></>}
 <div hidden={tab!=='specifications'}>{!data.specifications.length?<EmptyState title="Wycena jest przed nami">Gdy pracownia przygotuje specyfikację, zobaczysz tutaj cenę, wymiary i termin do zaakceptowania.</EmptyState>:data.specifications.map(s=><SpecificationCard key={s.id} spec={s}>{s.status==='offered'&&s.expires>Date.now()&&!['shipped','cancelled'].includes(data.stage)&&<ServiceForm submit="Zapisz decyzję" onSend={f=>send('decision',{specificationId:s.id,decision:f.get('decision'),note:f.get('note'),acknowledged:f.get('acknowledged')==='on'})}><label className="field">Twoja decyzja<select name="decision"><option value="accept">Akceptuję tę wersję</option><option value="changes">Proszę o zmianę</option></select></label><label className="field">Co zmienić? (wymagane przy prośbie o zmianę)<textarea name="note" maxLength={2000}/></label><label className="check"><input type="checkbox" name="acknowledged" required/>Sprawdziłem tę wersję, cenę, wymiary i termin. Decyzja nie pobiera płatności.</label></ServiceForm>}</SpecificationCard>)}</div>
 <div hidden={tab!=='messages'}><Conversation orderId={key.id} messages={data.messages} send={body=>send('messages',body)}/></div>
 {tab==='progress'&&<ol className="order-timeline">{Object.entries(stageNames).filter(([s])=>s!=='cancelled'||data.stage==='cancelled').map(([s,label])=>{const events=data.events.filter(e=>e.stage===s);return <li key={s} data-recorded={s==='received'||events.length>0} aria-current={data.stage===s?'step':undefined}><h3>{label}</h3>{events.length?events.map(e=><div key={e.id}><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString('pl-PL')}</time><p>{e.note}</p><div className="progress-photos">{e.photos.map(id=><ProtectedPhoto key={id} path={'/api/tracking/'+key.id+'/photos/'+id} token={key.token}/>)}</div></div>):<p>{s==='received'?'Zapisaliśmy zgłoszenie.':'Brak aktualizacji z tego etapu.'}</p>}</li>})}</ol>}
 {tab==='shipment'&&(data.shipment?<article className="service-state"><h3>InPost {data.shipment.environment==='sandbox'?'— przesyłka testowa':''}</h3><p>Numer: {data.shipment.tracking_number||'Jeszcze nie nadano'}</p><p>Status przewoźnika: {data.shipment.status}</p><p>Ostatnia aktualizacja: {new Date(data.shipment.updated_at).toLocaleString('pl-PL')}</p><p>Utworzenie etykiety nie oznacza przekazania paczki kurierowi.</p></article>:<EmptyState title="Przesyłka nie została jeszcze przygotowana">Numer i status pojawią się po przygotowaniu wysyłki przez pracownię. Przy odbiorze osobistym uzgodnimy termin w wiadomościach.</EmptyState>)}
 <div className="service-actions"><button disabled={loading} onClick={refresh}>Odśwież dane</button><button onClick={forget}>Usuń dostęp z tej karty</button></div></>:initialized&&!key?<EmptyState title="Otwórz swoje zamówienie">Użyj prywatnego linku z wiadomości e-mail lub odzyskaj go poniżej. Konto klienta nie jest potrzebne.</EmptyState>:null}
 <details open={!data}><summary>Odzyskaj dostęp do zamówienia</summary><ServiceForm submit="Wyślij nowy dostęp" onSend={async f=>{const r=await post<{message:string}>('/api/tracking-access',{id:f.get('id'),email:f.get('email')});setRecovered(r.message)}}><label className="field">Numer zamówienia<input name="id" required maxLength={36}/></label><label className="field">E-mail użyty w zamówieniu<input type="email" name="email" required maxLength={254}/></label></ServiceForm><p role="status">{recovered}</p></details></section></>
}
