import {useEffect,useState,type FormEvent} from 'react'
import {Link,useParams} from 'react-router-dom'
import {api,post} from '../lib/api'
import {useProducts} from '../state/store'
import {PageHeading,NotFound} from './Pages'
export const stageNames:Record<string,string>={received:'Do uzgodnienia',confirmed:'Przyjęte',cutting:'Krojenie',sewing:'Szycie',printing:'Nadruk',ready:'Gotowe',shipped:'Wysłane',cancelled:'Anulowane'}
export function ProtectedPhoto({path,token}:{path:string;token?:string}){
 const [src,setSrc]=useState(''),[error,setError]=useState(false)
 useEffect(()=>{let active=true,url='';setError(false);setSrc('');fetch(path,{headers:token?{Authorization:'Bearer '+token}:{},signal:AbortSignal.timeout(15000)}).then(async r=>{if(!r.ok)throw Error();url=URL.createObjectURL(await r.blob());if(active)setSrc(url);else URL.revokeObjectURL(url)}).catch(()=>{if(active)setError(true)});return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[path,token])
 return src?<img className="progress-photo" src={src} alt="Zdjęcie wykonania Twojej pary, dodane przez pracownię."/>:<p>{error?'Zdjęcie jest chwilowo niedostępne.':'Wczytujemy zdjęcie…'}</p>
}
interface Track {id:string;stage:string;estimatedDate:string|null;createdAt:string;products:{name:string;size:string;variant:string;quantity:number}[];events:{id:string;created_at:string;stage:string;note:string;photos:string[]}[]}
export function Tracking(){
 const [key,setKey]=useState<{id:string;token:string}|null>(null),[data,setData]=useState<Track|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[attempt,setAttempt]=useState(0),[busy,setBusy]=useState(false)
 useEffect(()=>{try{const fragment=window.location.hash.slice(1),match=fragment.match(/^([a-f0-9-]{36})\.([a-f0-9]{64})$/);if(match){const value={id:match[1],token:match[2]};sessionStorage.setItem('workshop.tracking',JSON.stringify(value));setKey(value);window.history.replaceState(null,'',window.location.pathname)}else setKey(JSON.parse(sessionStorage.getItem('workshop.tracking')||sessionStorage.getItem('workshop.receipt.v1')||'null'))}catch{setError('Nie można odczytać dostępu w tej przeglądarce.')}},[])
 useEffect(()=>{if(!key)return;let active=true;setError('');setData(null);api<Track>('/api/tracking/'+encodeURIComponent(key.id),{headers:{Authorization:'Bearer '+key.token}}).then(r=>{if(active)setData(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[key,attempt])
 async function recover(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const r=await post<{message:string}>('/api/tracking-access',{id:f.get('id'),email:f.get('email')});setMessage(r.message)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><PageHeading eyebrow="Twoja para / realizacja" title="Od ustaleń do wysyłki." text="Aktualizacje prosto z pracowni. Bez zakładania konta."/><section className="shell section solid-stage tracking-page">
 {error&&<p role="alert">{error} <button onClick={()=>setAttempt(n=>n+1)}>Ponów</button></p>}
 {data?<><div className="tracking-summary"><p className="eyebrow">Zamówienie {data.id}</p><h2>{stageNames[data.stage]}</h2><p>Przewidywany termin: <strong>{data.estimatedDate?new Date(data.estimatedDate+'T12:00:00').toLocaleDateString('pl-PL'):'jeszcze nieustalony'}</strong></p><p>Termin jest szacunkiem pracowni. Płatności na stronie są wyłączone.</p>{data.products.map((p,i)=><p key={i}>{p.name} · {p.size} · {p.variant} · {p.quantity} szt.</p>)}</div><ol className="order-timeline">{Object.entries(stageNames).filter(([s])=>s!=='cancelled'||data.stage==='cancelled').map(([stage,label])=>{const events=data.events.filter(e=>e.stage===stage);const done=stage==='received'||events.length>0;return <li key={stage} data-recorded={done} aria-current={data.stage===stage?'step':undefined}><h3>{label}</h3>{events.length?events.map(e=><div key={e.id}><time dateTime={e.created_at}>{new Date(e.created_at).toLocaleString('pl-PL')}</time><p>{e.note}</p><div className="progress-photos">{e.photos.map(id=><ProtectedPhoto key={id} path={'/api/tracking/'+data.id+'/photos/'+id} token={key!.token}/>)}</div></div>):<p>{stage==='received'?'Zgłoszenie zapisane.':'Brak aktualizacji z tego etapu.'}</p>}</li>})}</ol><button onClick={()=>setAttempt(n=>n+1)}>Odśwież status</button><button onClick={()=>{sessionStorage.removeItem('workshop.tracking');sessionStorage.removeItem('workshop.receipt.v1');setKey(null);setData(null)}}>Usuń dostęp z tej karty</button></>:key&&!error?<p role="status">Pobieramy realizację…</p>:null}
 <details open={!data}><summary>Odzyskaj dostęp do zamówienia</summary><form onSubmit={recover}><label className="field">Numer zamówienia<input name="id" required maxLength={36}/></label><label className="field">E-mail użyty przy zamówieniu<input name="email" type="email" required maxLength={254}/></label><button className="btn" disabled={busy}>Wyślij nowy dostęp</button><p role="status">{message}</p></form></details></section></>
}
export function Personalization(){
 const {slug}=useParams(),product=useProducts().find(p=>p.slug===slug)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[id,setId]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const result=await post<{id:string}>('/api/personalizations',{slug,name:f.get('name'),email:f.get('email'),material:f.get('material'),print:f.get('print'),inseam:Number(f.get('inseam')),waist:Number(f.get('waist')),hips:Number(f.get('hips')),notes:f.get('notes'),acknowledged:f.get('acknowledged')==='on'});setId(result.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!product)return <NotFound/>
 return <><PageHeading eyebrow={'Personalizacja / '+product.name} title="Para według Twoich wymiarów." text="Prześlij pomysł. Pracownia potwierdzi możliwości, cenę i termin przed przyjęciem do wykonania."/><section className="shell section solid-stage tool-reading">{id?<div role="status"><h2>Pomysł zapisany.</h2><p>Numer zapytania: {id}. Czekaj na indywidualną wycenę. Nie pobrano płatności.</p></div>:<form onSubmit={submit}>{[['name','Imię i nazwisko','text'],['email','E-mail','email']].map(([name,label,type])=><label className="field" key={name}>{label}<input name={name} type={type} required maxLength={name==='email'?254:100}/></label>)}<div className="measure-grid">{[['material','Materiał',product.customMaterials||[product.material]],['print','Nadruk',product.customPrints||[product.printStyle]]].map(([name,label,values])=><label className="field" key={String(name)}>{label}<select name={String(name)}>{(values as string[]).map(v=><option key={v}>{v}</option>)}</select></label>)}</div><p>Podaj obwody ciała oraz docelową długość wewnętrzną nogawki w cm.</p><div className="measure-grid">{[['waist','Pas'],['hips','Biodra'],['inseam','Nogawka']].map(([name,label])=><label className="field" key={name}>{label}<input name={name} type="number" min="20" max="250" step="0.5" required/></label>)}</div><label className="field">Dodatkowe wymiary i pomysł na dekorację<textarea name="notes" maxLength={1500}/></label><label className="check"><input type="checkbox" name="acknowledged" required/><span>Znam <Link to="/privacy">informację o prywatności</Link>. To zapytanie o wycenę, nie potwierdzone zamówienie.</span></label>{error&&<p role="alert">{error}</p>}<button className="btn" disabled={busy||product.available===false}>{busy?'Zapisujemy…':'Poproś o wycenę'}</button></form>}</section></>
}
export function NewsletterAction(){
 const [action,setAction]=useState<{purpose:string;token:string}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const match=window.location.hash.slice(1).match(/^(confirm|unsubscribe)\.([a-f0-9]{64})$/);if(match){setAction({purpose:match[1],token:match[2]});window.history.replaceState(null,'',window.location.pathname)}},[])
 async function submit(){if(!action)return;setBusy(true);try{await post('/api/newsletter/action',action);setMessage(action.purpose==='confirm'?'Zapis potwierdzony.':'Adres został wypisany.');setAction(null)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><PageHeading eyebrow="Wiadomości z pracowni" title="Twój wybór wiadomości."/><section className="shell section solid-stage tool-reading">{action?<button className="btn" disabled={busy} onClick={submit}>{action.purpose==='confirm'?'Potwierdzam zapis':'Wypisz mnie'}</button>:!message?<p>Otwórz link z wiadomości e-mail.</p>:null}<p role="status">{message}</p></section></>
}

