/* Generated by scripts/audit-palette.mjs. Do not edit by hand. */

export const SHADER_PALETTE = {
  sumiVoid: '#06070a',
  sumi: '#0f1014',
  sumiLift: '#191c21',
  sumiLine: '#35383e',
  washi: '#f4f2ee',
  washiDeep: '#e2dfd8',
  washiLine: '#b4b1a9',
  kin: '#bbab85',
  shu: '#ce3d2d',
  shuLift: '#e05f4d',
  shuDeep: '#9a2519',
  ai: '#223859',
} as const

export type ShaderPaletteKey = keyof typeof SHADER_PALETTE
