/* ==========================================================================
   Palette audit.

   Resolves every OKLCH token to sRGB hex for the WebGL shaders, which need
   numeric colour, and verifies the contrast claims DESIGN.md makes. Run it
   whenever a token changes:

       node scripts/audit-palette.mjs

   Exit code 1 means a documented contrast pair has fallen below AA.
   ========================================================================== */

const TOKENS = {
  'sumi-void': [0.13, 0.006, 265],
  sumi: [0.175, 0.008, 265],
  'sumi-lift': [0.225, 0.01, 265],
  'sumi-line': [0.34, 0.012, 265],
  washi: [0.962, 0.006, 90],
  'washi-deep': [0.905, 0.01, 88],
  'washi-line': [0.76, 0.012, 88],
  kin: [0.745, 0.055, 88],
  shu: [0.572, 0.185, 30],
  'shu-lift': [0.645, 0.165, 30],
  'shu-deep': [0.455, 0.155, 30],
  ai: [0.34, 0.065, 258],
}

/** Pairs DESIGN.md documents as passing, with the WCAG level they must reach. */
const REQUIRED = [
  ['washi', 'sumi', 7, 'body text on ink'],
  ['washi', 'sumi-void', 7, 'body text on the deepest ground'],
  ['sumi', 'washi', 7, 'body text on paper'],
  ['sumi', 'washi-deep', 7, 'body text on a raised paper surface'],
  ['kin', 'sumi', 4.5, 'aged gold labels on ink'],
  ['kin', 'sumi-void', 4.5, 'aged gold labels on the deepest ground'],
  ['shu-lift', 'sumi', 4.5, 'vermilion text on ink'],
  ['shu-lift', 'sumi-void', 4.5, 'vermilion text on the deepest ground'],
  ['washi', 'shu-deep', 4.5, 'label inside a vermilion button'],
  ['sumi', 'washi', 4.5, 'label inside a paper button'],
  ['shu-deep', 'washi', 4.5, 'vermilion text on paper'],
  ['washi', 'shu', 3, 'seal glyph, large text only'],
  ['washi', 'sumi-lift', 7, 'body text on a raised ink surface'],
  ['kin', 'sumi-lift', 4.5, 'aged gold labels on a raised ink surface'],
  ['sumi', 'washi-line', 4.5, 'text against a paper hairline'],

  // Hairlines are non-text, so WCAG sets no minimum. They still have to be
  // perceptible, because DESIGN.md gives them all the structural work a
  // shadow would otherwise do.
  ['sumi-line', 'sumi', 1.6, 'hairline on ink, must be perceptible'],
  ['sumi-line', 'sumi-void', 1.6, 'hairline on the deepest ground'],
  ['washi-line', 'washi', 1.35, 'hairline on paper, must be perceptible'],
]

function oklchToLinear([L, C, H]) {
  const h = (H * Math.PI) / 180
  const a = C * Math.cos(h)
  const b = C * Math.sin(h)

  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3

  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ]
}

const gamma = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055)

function oklchToRgb(token) {
  return oklchToLinear(TOKENS[token]).map((channel) =>
    Math.round(Math.min(1, Math.max(0, gamma(channel))) * 255),
  )
}

const hex = (token) =>
  `#${oklchToRgb(token)
    .map((channel) => channel.toString(16).padStart(2, '0'))
    .join('')}`

/**
 * WCAG relative luminance. oklchToLinear already returns linear-light RGB,
 * which is exactly what the luminance formula consumes, so no gamma step
 * belongs here. Applying one would crush the dark end of the palette.
 */
function luminance(token) {
  const [r, g, b] = oklchToLinear(TOKENS[token])
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

function contrast(foreground, background) {
  const a = luminance(foreground)
  const b = luminance(background)
  const [hi, lo] = a > b ? [a, b] : [b, a]
  return (hi + 0.05) / (lo + 0.05)
}

/* --- Report -------------------------------------------------------------- */

console.log('\n  sRGB values for the WebGL shaders\n')
for (const token of Object.keys(TOKENS)) {
  const [oklchL, oklchC, oklchH] = TOKENS[token]
  console.log(
    `  ${token.padEnd(12)} ${hex(token)}   oklch(${oklchL} ${oklchC} ${oklchH})`,
  )
}

console.log('\n  Contrast against the documented requirement\n')

let failures = 0
for (const [foreground, background, required, purpose] of REQUIRED) {
  const actual = contrast(foreground, background)
  const pass = actual >= required
  if (!pass) failures += 1
  console.log(
    `  ${pass ? 'pass' : 'FAIL'}  ${actual.toFixed(2).padStart(6)}:1  ` +
      `(need ${required})  ${foreground} on ${background}`.padEnd(52) +
      `  ${purpose}`,
  )
}

console.log(
  failures === 0
    ? `\n  All ${REQUIRED.length} documented pairs hold.\n`
    : `\n  ${failures} pair(s) below requirement. Fix the token or the claim.\n`,
)

/* Emit a TS module the shaders import, so hex and OKLCH cannot drift. */
const emitted = [
  '/* Generated by scripts/audit-palette.mjs. Do not edit by hand. */',
  '',
  'export const SHADER_PALETTE = {',
  ...Object.keys(TOKENS).map(
    (token) => `  ${token.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}: '${hex(token)}',`,
  ),
  '} as const',
  '',
  'export type ShaderPaletteKey = keyof typeof SHADER_PALETTE',
  '',
].join('\n')

const { writeFileSync, mkdirSync } = await import('node:fs')
mkdirSync('src/components/three/shaders', { recursive: true })
writeFileSync('src/components/three/shaders/palette.ts', emitted)
console.log('  Wrote src/components/three/shaders/palette.ts\n')

process.exit(failures === 0 ? 0 : 1)
